name: Release (train, docker, GHCR, notes)

on:
  push:
    tags:
      - 'v*'      # e.g. v0.1, v0.2
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

env:
  IMAGE: ghcr.io/yuzhunn/diabetes-triage-mlops
  PYTHON_VERSION: '3.11'
  PORT: '8000'

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train model (auto choose by tag)
        shell: bash
        run: |
          TAG="${GITHUB_REF_NAME}"
          echo "Detected tag: $TAG"

          if [ "$TAG" = "v0.1" ]; then
            echo "Training linear model for v0.1"
            python src/train.py --model linear
          else
            echo "Training ridge model for $TAG"
            python src/train.py --model ridge --alpha 30
          fi

          echo "---- metrics ----"
          cat models/metrics.json || true
          echo "---- model_version ----"
          cat models/model_version.txt || true

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: |
          TAG="${GITHUB_REF_NAME}"
          docker build -t $IMAGE:${TAG} -t $IMAGE:latest .

      - name: Smoke test container
        run: |
          TAG="${GITHUB_REF_NAME}"
          docker run -d -p ${PORT}:${PORT} --name svc $IMAGE:${TAG}

          echo "Waiting for /health ..."
          for i in {1..30}; do
            sleep 1
            if curl -fsS "http://127.0.0.1:${PORT}/health" >/dev/null; then break; fi
          done

          curl -fsS "http://127.0.0.1:${PORT}/health"
          curl -fsS -X POST "http://127.0.0.1:${PORT}/predict" \
            -H "Content-Type: application/json" \
            -d '{"age":0.02,"sex":-0.044,"bmi":0.06,"bp":-0.03,"s1":-0.02,"s2":0.03,"s3":-0.02,"s4":0.02,"s5":0.02,"s6":-0.001}' | jq .
          docker rm -f svc

      - name: Push image
        run: |
          TAG="${GITHUB_REF_NAME}"
          docker push $IMAGE:${TAG}
          docker push $IMAGE:latest

      - name: Read metrics
        id: m
        run: |
          echo "rmse=$(jq -r '.rmse' models/metrics.json)" >> $GITHUB_OUTPUT
          echo "model_version=$(cat models/model_version.txt)" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            ## Metrics
            - RMSE: ${{ steps.m.outputs.rmse }}
            - Model version: ${{ steps.m.outputs.model_version }}
            See CHANGELOG.md for details.
          files: |
            models/metrics.json
            models/model_version.txt
